### PR TITLE
Added missing country parameter

### PR DESCRIPTION
**Pull request by Seba-T**
Typescript wouldn't compile due to the missing country parameter, so I added it

### CODE REVIEW

**Comment by victory-sokolov** [comment]
Why did you change the name of the package?

**Comment by Seba-T** [comment]
Because I published an npm packaged to attempt to deploy it on hekoru and check everything was working properly, now I'm gonna revert the changes to the README and package.json

**Comment by victory-sokolov** [comment]
Thanks for contributing!
Could you please format code to 4 spaces instead of 2 for consistency.
Thank you!

**Comment by Seba-T** [comment]
fixed it!

**Comment by victory-sokolov** [comment]
Closed in favor of https://github.com/nordigen/nordigen-node/pull/33
Issue is fixed

**Pull request closed without merging**
